/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    "Information":"说明",

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'Reset for +': '重置获得 +',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //树游戏
    'Loading...': '加载中...',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'Play Again': '再次游戏(硬重置)',
    'Keep Going': '继续游戏',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Main Prestige Tree server': '主声望树服务器',
    '': '',
    '': '',
    "Dev Speed: ": "开发者加速: ",
}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " completions": " 完成",
    " (softcapped": " (软上限",
    " (softcapped)": " (软上限)",
    "": "",
    'SHOWN': '显示',
    "Default": "默认",
    "Aqua": "水色",
    'ALWAYS': '一直',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '已开',
    'OFF': '已关',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\^([\d\.]+)$/,
    /^\^([\d\.]+)x$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\d\.]+)e(\d+)x$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
/*
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^Base level, xp & gold gain is powered to \^(.+) \(before this layer effect$/, '基础等级，经验和金币获取的效果提高到 \^$1（在此层效果之前'],
    [/^Upgrade 3,1 power goes from (.+)\/(.+) to (.+)\/(.+)$/, '升级3,1的效果从$1\/$2增加到$3\/$4'],
    [/^You have made a total of (.+) gold$/, '你总共赚了 $1 金币'],
    [/^Cost\: (.+) rubies\n(.+)Amount\: (.+)\n(.+)XP and gold base exponents are powered to (.+)$/, '成本\: $1 红宝石\n数量\: $3\n交易和黄金基础指数提升到 $5'],
    [/^Cost\: (.+) rubies\n(.+)Amount\: (.+)\n(.+)Base lvl gain exponent is powered to (.+)$/, '成本\: $1 红宝石\n数量\: $3\n基本等级收益指数提高 $5'],
    [/^Cost\: (.+) loot\n(.+)Amount\: (.+)\n(.+) Gold Gain mult is powered to \^(.+)$/, '成本：$1战利品\n数量：$3\n黄金增益多重增强 ^$5'],
    [/^Cost\: (.+) loot\n(.+)Amount\: (.+)\n(.+) XP Gain mult is powered to \^(.+)$/, '成本：$1战利品\n数量：$3\n经验增益多重增强 ^$5'],
    [/^Cost\: (.+) xp\n(.+)Amount\: (.+)\n(.+)Generate (.+)\% gold per second, lol it\'s kinda obvious$/, '成本：$1经验\n数量：$3\n每秒产生 $4\％ 黄金, 哈哈，这是很明显的'],
    [/^Cost\: (.+) xp\n(.+)Amount\: (.+)\n(.+)Generate x(.+) gold per second, lol it\'s kinda obvious$/, '成本：$1经验\n数量：$3\n每秒产生 x$4 黄金, 哈哈，这是很明显的'],
    [/^Cost\: (.+) gold\n(.+)Amount\: (.+)\n(.+)Generate (.+)\% XP per second$/, '成本：$1黄金\n数量：$3\n每秒产生$4\％经验值'],
    [/^Cost\: (.+) gold\n(.+)Amount\: (.+)\n(.+)Generate x(.+) XP per second$/, '成本：$1黄金\n数量：$3\n每秒产生 x$4 经验值'],
    [/^Cost\: (.+) loot\n\t\t$/, '成本\: $1 战利品\n\t\t'],
    [/^Cost\: (.+) rubies\n\t\t$/, '成本\: $1 红宝石\n\t\t'],
    [/^Cost\: (.+) experience\n\t\t$/, '成本\: $1 经验\n\t\t'],
    [/^Cost\: (.+) gold\n\t\t$/, '成本\: $1 黄金\n\t\t'],
    [/^Cost\: (.+) gold\n\t\t$/, '成本\: $1 黄金\n\t\t'],
    [/^Cost\: (.+) levels\n\t\t$/, '成本\: $1 级\n\t\t'],
    [/^Cost\: (.+) treasures\n\t\t$/, '成本\: $1 珍宝\n\t\t'],
    [/^Autobuy up to (.+) passive upgrades\/tick$/, '自动购买高达 $1 被动升级\/tick'],
    [/^Get (.+) max rubies$/, '获得 $1 个最大红宝石'],
    [/^Get (.+) quests$/, '获得 $1 个任务'],
    [/^Get (.+) skills$/, '获得 $1 技能'],
    [/^Get (.+) skill$/, '获得 $1 技能'],
    [/^, Treasures help you get more skills. Lol. Increases your max level by (.+). Increases your skill powered gain by (.+)\%. Needs 60 really last \(9\) quest challenge competitions for treasure prestige.$/, '，宝物助你获得更多技能。 哈哈。 将您的最高等级提高 $1。 将你的技能能量增益提高 $2\%。 需要 60 真最后 \(9\) 任务挑战赛才能获得宝物声望。'],
    [/^, Skills can make you level up and complete first two layers faster. Total S. divides loot, quests and ruby exp by (.+). Multiplies XP and gold exponents by (.+). Needs 100 last \(8\) quest challenge competitions for skill prestige.$/, '，技能可以让你升级并更快地完成前两层。 总 S. 将战利品、任务和红宝石经验除以 $1。 将 XP 和黄金指数乘以 $2。 需要 100 次最后 \(8\) 次任务挑战赛才能获得技能声望。'],
    [/^Exp, Gold and Level gain are set to (.+). Their base exponents are also set to (.+)$/, '经验，黄金和等级增益设置为 $1。 他们的基本指数也设置为 $2'],
    [/^total skills squared:  \+(.+) \(Hardcapped at (.+)\). \+(.+) 2nd ruby buyables\/tick.$/, '总技能平方：\+$1（上限为$2）。 \+$3第二颗红宝石可买\/tick。'],
    [/^You can progress faster. Multiplies xp, gold and level gain by (.+)\^\(total_upgrades\). Now\: x(.+)$/, '您可以更快地进步。 将经验，黄金和等级增益乘以 $1\^（总计升级）。 现在：x$2'],
    [/^You are gaining (.+) skills per second$/, '你每秒获得 $1 技能'],
    [/^Treasure effects are (.+) times more effective but still affected by the softcap$/, '宝藏效果提高了 $1 倍，但仍然受到软上限的影响'],
    [/^\t\t\tGoal\: (.+) level$/, '\t\t\t目标\: $1 级'],
    [/^, loot will help you level up much faster, your best loot will multiply your Lv \& XP gain by (.+). \(You should wait at least until (.+) or (.+) for better effect$/, '，战利品将帮助您更快地升级，最好的战利品将使您的等级和建议增益乘以$1。 （您应该至少等到$2或$3才能获得更好的效果'],
    [/^You have (.+) levels$/, '你有 $1 等级'],
    [/^Level, Exp and Gold gain are powered to \^(.+). This challenge reward doesn\'t work here.$/, '等级、经验和黄金增益为 \^$1。这个挑战奖励在这里不起作用。'],
    [/^\t\t\tGoal\: (.+) exp$/, '\t\t\t目标: $1 经验'],
    [/^You have made a total of (.+) skills$/, '您总共取得了 $1 的技能'],
    [/^Quest bonus exponent to loot multiplied by (.+). XP softcap starts (.+) later. \(At (.+)$/, '任务奖励指数乘以$1。经验软上限在$2之后启动。\(在 $3'],
    [/^You are gaining (.+) treasures per second$/, '您每秒获得 $1 珍宝'],
    [/^Next at (.+) levels$/, '下一个在 $1 级'],
    [/^Next\: (.+) \/ (.+) gold\t\t\n\t\t$/, '下一个\: $1 \/ $2 黄金\t\t\n\t\t'],
    [/^Next\: (.+) \/ (.+) exp\t\t\n\t\t$/, '下一个\: $1 \/ $2 经验\t\t\n\t\t'],
    [/^(.+) \/ (.+) gold\t\t\n\t\t$/, ' $1 \/ $2 黄金\t\t\n\t\t'],
    [/^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+) xp\t\t\n\t\t$/, ' $1e$2 \/ $3e$4 经验\t\t\n\t\t'],
    [/^([\d\.]+)e([\d\.,]+) \/ e([\d\.]+)e([\d\.,]+) exp\t\t\n\t\t$/, ' $1e$2 \/ $3e$4 经验\t\t\n\t\t'],
    [/^e([\d\.,]+)e([\d\.]+) \/ e([\d\.]+)e([\d\.,]+) exp\t\t\n\t\t$/, ' $1e$2 \/ $3e$4 经验\t\t\n\t\t'],
    [/^Req\: (.+) \/ (.+) gold\t\t\n\t\t$/, '要求\: $1 \/ $2 黄金\t\t\n\t\t'],
    [/^Req\: (.+) \/ (.+) exp\t\t\n\t\t$/, '要求\: $1 \/ $2 经验\t\t\n\t\t'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
*/
]);